server:
  port: 8090
spring:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  datasource:
    password: ''
    username: root
    url: jdbc:h2:mem:testdb
  cloud:
    function:
      definition: brewBeerInventory;allocateOrder|allocateOrderResult;dealocateOrderRequestConsumer
    stream:
      bindings:
        brewBeerInventory-in-0:
          destination: brew-beer-inventory
          group: ${spring.application.name}
        allocateOrderallocateOrderResult-in-0:
          destination: allocation-request
          group: ${spring.application.name}
        allocateOrderallocateOrderResult-out-0:
          destination: allocation-result
        dealocateOrderRequestConsumer-in-0:
          destination: dealocate-order-request
          group: ${spring.application.name}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: false


management:
  endpoint:
    metrics:
      enabled: true
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true


logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

endpoints:
  shuwdown:
    enabled: true
